apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: dart-messages
        role: backend
        type: database
    spec:
      containers:
        - name: postgresql
          image: postgres:9.6
          envFrom:
            - secretRef:
                name: secrets
            - configMapRef:
                name: config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: volume-claim