# apiVersion: v1
# kind: Service
# metadata:
#   name: web-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: dart-messages
#     role: frontend
#   ports:
#     - port: 80
#       targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: dart-messages
    role: frontend
  ports:
    - port: 80
      targetPort: 80